logging:
  level:
    org:
      atmosphere: warn
server:
  port: ${PORT:8080}
spring:
  jpa:
    defer-datasource-initialization: true
  mustache:
    check-template-location: false
vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
info:
  application:
    name: my-app
    description: Приложение
    version: '@project.version@'
    spring-boot-version: '@project.parent.version@'
management:
  endpoints:
    web:
      exposure:
        include: '*' 
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    java:
      enabled: true
    build:
      enabled: true
    env:
      enabled: true
    os:
      enabled: true
    git:
      enabled: true
